### ISSUE TITLE
OWLERY: Load barebones logic

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/owlery-vfb#8]
Import:
1) bare logic (no annotations)
2) just fbbt, kb, vfb-ext (we can use contexts to distinguish what should be loaded.)

PDB should have inference, owlery probably not.

**Comment by matentzn** [comment]
@Robbie1977 is setting up a branch on the container to redirect to the new dump.

**Comment by matentzn** [comment]
as discussed in https://github.com/VirtualFlyBrain/vfb-pipeline-config/issues/18, we also need:

- [x] a Reduce step
- [x] handling of unsatisfiable classes
- [x] We also need to keep the disjoint axioms as much as possible

**Comment by matentzn** [comment]
The owlery dump is defined [here](https://github.com/VirtualFlyBrain/vfb-pipeline-dumps/blob/c101f7d13377a30a1757519cb508a47c2d95da5a/dumps.Makefile#L68).

Since it inherits from `dump_all.owl`, it is reduced.

**Comment by matentzn** [comment]
The endpoint is here: http://owl.p2.virtualflybrain.org/kbs/vfb

**Comment by dosumis** [comment]
Performance is great!
